apiVersion: apps/v1
kind: Deployment
metadata:
  name: webappservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webappservice
  template:
    metadata:
      labels:
        app: webappservice
    spec:
      containers:
      - name: webappservice
        image: deepakbedase/netcore:v2
        ports:
        - containerPort: 80
        env:
        - name: SIMPLE_SERVICE_VERSION
          value: "0.9"
