apiVersion: v1
kind: ReplicationController
metadata:
  name: rcwebapp
spec:
  replicas: 1
  selector:
    app: rcwebapp
  template:
    metadata:
      name: rcwebapp
      labels:
        app: rcwebapp
    spec:
      containers:
      - name: rcwebapp
        image: deepakbedase/netcore:v2
        ports:
        - containerPort: 80
